services:
  firebase-emulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9099:9099 # Auth
      - 4000:4000 # Emulator Suite UI
    tty: true
    volumes:
      - ./data:/home/node/data
      - ./firebase.json:/home/node/firebase.json
